sonar.projectKey=DayronCasas_AS241S5_AEJ_06-fe
sonar.organization=dayroncasas

# Nombre y versión mostrados en la UI de SonarCloud
sonar.projectName=AS241S5_AEJ_06-fe
sonar.projectVersion=1.0

# Rutas de código fuente
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# TypeScript
sonar.typescript.tsconfigPath=tsconfig.app.json
sonar.sourceEncoding=UTF-8
